In [3]:
import numpy as np
arr=([1,2,3,4,5,6,7,8,9,10])
q=arr[5:9]
print(q)

[6, 7, 8, 9]


In [8]:
import numpy as np
ar3=([[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]])
s=ar3[2:4:4]
print(s)

([[17, 18, 19, 20], [21, 22, 23, 24]],)


## RANDOM MODEL

In [4]:
import numpy as np
ar1 = np.arange(2,15)
print(ar1)
ar2= np.arange(1,20,1.5)
print(ar2)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13.  14.5 16.  17.5 19. ]


### RandomModule

In [24]:
import numpy as np
import random
a1= np.random.random(23)
print(a1)
np.random.seed(10)
a2=np.random.randint(5,15,5)
print(a2)

[0.58332174 0.02517173 0.70920801 0.26556613 0.26360285 0.15037787
 0.68381843 0.81660184 0.33607158 0.89081653 0.19812181 0.03061665
 0.87761494 0.72743551 0.54088093 0.13145815 0.41366737 0.77872881
 0.58390137 0.18263144 0.82608225 0.10540183 0.28357668]
[14  9  5  6 14]


## Problem
Give  Daily Sales of a shop for 7 days.
[1200, 1800, 1500, 7000, 8000, 1700, 5500]
1. find total sale (week)
2. Average sale
3. highest sale and lowest sales
4. day no. when the highest sales happen

In [3]:
import numpy as np
ar1=np.array([1200, 1800, 1500, 7000, 8000, 1700, 5500])
print(ar1)
total_sale = np.sum(ar1)
print("Total Sale(week) :" , total_sale)
high_sale = np.max(ar1)
print("Max sale :", high_sale)
low_sale = np.min(ar1)
print("Min Sale :", low_sale)
avrage_sale = np.mean(ar1)
print("Avg Sale :",avrage_sale)
day_high = np.argmax(ar1) +1
print("Highest Sale Day :",day_high)


[1200 1800 1500 7000 8000 1700 5500]
Total Sale(week) : 26700
Max sale : 8000
Min Sale : 1200
Avg Sale : 3814.285714285714
Highest Sale Day : 5


## Problem
Electricity Bill Calculation
You have unit consumed for each day of a month(30 days)
1. Calculate daily bill (per unit bill=7.5
2. Calculate Monthly Bill
3. Highest and lowest unit consumption
4. Day no. when high unit consumption